openapi: 3.0.3
info:
  title: Music
  version: 1.0.0
  description: 'project description: singer, album, song, content'
paths:
  /api/album/:
    get:
      operationId: album_list
      description: A simple ViewSet for getting all albums.
      tags:
      - album
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'
          description: ''
  /api/content:
    get:
      operationId: content_list
      tags:
      - content
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
          description: ''
    post:
      operationId: content_create
      tags:
      - content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Content'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Content'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Content'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
          description: ''
  /api/singer/:
    get:
      operationId: singer_list
      description: A simple ViewSet for getting all singers.
      tags:
      - singer
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Singer'
          description: ''
  /api/song/:
    get:
      operationId: song_list
      description: A simple ViewSet for getting all songs.
      tags:
      - song
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Song'
          description: ''
components:
  schemas:
    Album:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 100
        singer:
          type: integer
        year:
          type: integer
      required:
      - id
      - singer
      - title
      - year
    Content:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        song:
          type: integer
        track_number:
          type: integer
        album:
          type: integer
      required:
      - album
      - id
      - song
      - track_number
    Singer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    Song:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 100
      required:
      - id
      - title
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
